name: Build and Test Common Build Image

on:
  push:
    branches: [main]
    paths:
      - 'images/common-build/**'
      - '.github/workflows/build_common_image.yml'
  pull_request:
    branches: [main]
    paths:
      - 'images/common-build/**'
      - '.github/workflows/build_common_image.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Common Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: latest

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Build Image
        working-directory: images/common-build
        run: packer build -var-file=variables.pkr.hcl common_build.pkr.hcl

      - name: Test Image
        run: |
          docker run --rm your-dockerhub-username/common-build-image:latest bash -c "/test_image.sh"

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        if: github.event_name != 'pull_request'
        run: docker push your-dockerhub-username/common-build-image:latest
